apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::006808541377:user/user-project4
      username: user-project4
      groups:
        - system:bootstrappers
        - system:nodes