apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-capstone
  labels:
    app: ml-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ml-capstone
    spec:
      containers:
        - image: shironguyen/ml-capstone:latest
          imagePullPolicy: Always
          name: ml-capstone
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-capstone
  labels:
    app: ml-capstone
spec:
  type: LoadBalancer
  selector:
    app: ml-capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP